version: "3.9"

services:
  web:
    image: dawidmalina/gh-actions-haproxy:3.17-b10
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ./docker/haproxy/default.pem
        target: /etc/ssl/certs/default.pem
        read_only: true
    environment:
      PRINT_CONFIG: true
      BACKEND_1: 172.16.238.11:80
      BACKEND_2: 172.16.238.12:80
      BACKEND_3: 172.16.238.13:80
      CERTIFICATE: /etc/ssl/certs/default.pem
    networks:
      internal:
        ipv4_address: 172.16.238.100

  backend_1:
    image: dawidmalina/gh-actions-nginx:1.23.2-b11
    expose:
      - 80
    environment:
      ADD_CUSTOM_MESSAGE: Nice one
    networks:
      internal:
        ipv4_address: 172.16.238.11

  backend_2:
    image: dawidmalina/gh-actions-nginx:1.23.2-b11
    expose:
      - 80
    environment:
      ADD_CUSTOM_MESSAGE: Nice two
    networks:
      internal:
        ipv4_address: 172.16.238.12

  backend_3:
    image: dawidmalina/gh-actions-nginx:1.23.2-b11
    expose:
      - 80
    environment:
      ADD_CUSTOM_MESSAGE: Nice three
    networks:
      internal:
        ipv4_address: 172.16.238.13

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"