# Pull the minimal oficial nginx image based on alpine
FROM haproxy:lts-alpine3.17

# Add information about maintainer
LABEL maintainer=Dawid Malinowski <dawidmalina@gmail.com>

# Copy configuration
# COPY ./haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg