# Pull the minimal oficial nginx image based on alpine
FROM nginx:1.23.2-alpine

# Add information about maintainer
LABEL maintainer=Dawid Malinowski <dawidmalina@gmail.com>

# Copy test html page
COPY ./index.html /usr/share/nginx/html/index.html

