name: Build and publish docker images
on:
  # run it on push to the default repository branch
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: ./docker/haproxy
            image: gh-actions-haproxy:latest
          - path: ./docker/nginx
            image: gh-actions-nginx:latest
    # steps to perform in job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.path }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
